#!/usr/bin/env python3
"""Generate every Leave-One-Municipality-Out config, for all eight baselines.

Each config is derived from its standard-benchmark counterpart under configs/,
with the data directory repointed at one municipality's LOMO split.

This script is the single source of truth for the LOMO configs: it writes all
8 baselines x 6 municipalities so that every LOMO run shares one set of
hyperparameters (learning rate 5e-5, batch size 8 for the Transformer
configurations), matching the standard-benchmark settings reported in the paper.
The earlier hand-written configs for deberta_crf and xlmr_crf used batch size 16;
regenerating with --overwrite replaces them, which is why the camera-ready runs
are a full re-run rather than a top-up of the existing results.

Usage:
    python scripts/make_lomo_configs.py --overwrite  # regenerate all 48
    python scripts/make_lomo_configs.py --dry-run    # list what would change
"""

import argparse
from pathlib import Path

import yaml

MUNICIPALITIES = ["M01", "M02", "M03", "M04", "M05", "M06"]

BASELINES = [
    "bert_crf",
    "deberta_crf",
    "xlmr_crf",
    "bert_linear",
    "deberta_linear",
    "xlmr_linear",
    "bilstm_fasttext",
    "crf",
]

# Applied to Transformer configs only; the BiLSTM and feature CRF keep their own
# published settings.
TRANSFORMER_OVERRIDES = {"learning_rate": "5e-5", "batch_size": 8}

# Every LOMO run is one SLURM task with `--gpus=1`, so the only CUDA ordinal that
# exists inside the allocation is 0. A source config naming a different device
# (configs/deberta_crf.yaml used to say `device: 1`) propagates into all six of
# its folds and makes src/trainer.py raise "Device 1 not available" at init, i.e.
# after the queue wait but before any training. Pin it here so no source config
# can reintroduce that.
SINGLE_GPU_ORDINAL = 0

SRC_DIR = Path("configs")
OUT_DIR = Path("configs/municipality_experiments")
SPLIT_DIR = "data/citilink-votie-lomo-splits"


def build(baseline: str, municipality: str) -> dict:
    config = yaml.safe_load((SRC_DIR / f"{baseline}.yaml").read_text())

    config["data"]["data_dir"] = f"{SPLIT_DIR}/{municipality}"
    config["data"]["train_file"] = "train.jsonl"
    config["data"]["dev_file"] = "dev.jsonl"
    config["data"]["test_file"] = "test.jsonl"

    training = config.setdefault("training", {})
    if "model_name" in config.get("model", {}):
        for key, value in TRANSFORMER_OVERRIDES.items():
            training[key] = value
    training["seed"] = 42
    # Only for configs that select a device at all; the feature CRF has no such key.
    if "device" in training:
        training["device"] = SINGLE_GPU_ORDINAL

    return config


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--overwrite", action="store_true",
                        help="Replace configs that already exist")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written, skipped = [], []

    for baseline in BASELINES:
        if not (SRC_DIR / f"{baseline}.yaml").exists():
            print(f"WARNING: no source config for {baseline}, skipping")
            continue
        for municipality in MUNICIPALITIES:
            out = OUT_DIR / f"{baseline}_{municipality}.yaml"
            if out.exists() and not (args.overwrite or args.dry_run):
                skipped.append(out.name)
                continue
            if args.dry_run:
                written.append(out.name)
                continue
            header = (
                f"# {baseline} — Leave-One-Municipality-Out: {municipality} as test set\n"
                f"# Generated by scripts/make_lomo_configs.py — do not edit by hand.\n\n"
            )
            body = yaml.safe_dump(build(baseline, municipality), sort_keys=False)
            out.write_text(header + body)
            written.append(out.name)

    verb = "Would write" if args.dry_run else "Wrote"
    print(f"{verb} {len(written)} config(s); skipped {len(skipped)} already present.")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
