#!/usr/bin/env python3
"""Generate the qualitative error-example table (Appendix) from error_classification_results.json.

Addresses reviewer iyoP's request for concrete error examples alongside the
aggregate error counts in Table 3.

Usage:
    python scripts/make_error_examples_table.py [--results PATH] [--out PATH]
"""

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Curated selection: each row illustrates a distinct, linguistically explainable
# failure mode rather than a random sample. (model, category, index_in_examples)
SELECTION = [
    ("XLM-R-CRF", "INC_BOUNDARY", 0),
    ("Gemini-Few-Shot", "INC_BOUNDARY", 0),
    ("Gemini-Few-Shot", "INC_BOUNDARY", 1),
    ("Gemini-Few-Shot", "INC_BOUNDARY", 2),
    ("Gemini-Few-Shot", "INC_TYPE", 1),
    ("Gemini-Few-Shot", "INC_TYPE", 2),
    ("Gemini-Few-Shot", "SPU", 0),
]

# Short English glosses explaining what went wrong.
GLOSS = {
    ("XLM-R-CRF", "INC_BOUNDARY", 0): "Truncates a long \\textsc{Subject} mid-clause.",
    ("Gemini-Few-Shot", "INC_BOUNDARY", 0): "Prepends the determiner \\textit{O}.",
    ("Gemini-Few-Shot", "INC_BOUNDARY", 1): "Includes the administrative framing preceding the subject.",
    ("Gemini-Few-Shot", "INC_BOUNDARY", 2): "Merges the outcome with its voter breakdown.",
    ("Gemini-Few-Shot", "INC_TYPE", 1): "Includes the honorific in a voter span.",
    ("Gemini-Few-Shot", "INC_TYPE", 2): "Absorbs the stance phrase and a second voter.",
    ("Gemini-Few-Shot", "SPU", 0): "Tags an infinitive as a voting act where no vote occurs.",
}

CAT_LABEL = {
    "INC_BOUNDARY": "BND",
    "INC_TYPE": "TYP",
    "SPU": "SPU",
    "MIS": "MIS",
}

MAXLEN = 78


def esc(s: str) -> str:
    """Escape LaTeX specials and collapse newlines."""
    if s is None:
        return "\\textit{(none)}"
    s = " ".join(s.split())
    for a, b in [
        ("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("$", "\\$"),
        ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}"),
        ("~", "\\textasciitilde{}"), ("^", "\\textasciicircum{}"),
    ]:
        s = s.replace(a, b)
    s = s.replace('"', "''")
    if len(s) > MAXLEN:
        s = s[: MAXLEN - 1].rstrip() + "\\ldots"
    return s


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=REPO / "results" / "error_classification_results.json")
    ap.add_argument("--out", default=REPO / "ACL_CitiLink___Vote_Identification__José_Evans_" / "latex" / "error_examples_table.tex")
    args = ap.parse_args()

    data = json.loads(Path(args.results).read_text(encoding="utf-8"))

    rows = []
    for model, cat, idx in SELECTION:
        examples = data[model]["example_errors"].get(cat, [])
        if idx >= len(examples):
            print(f"  ! skipping {model}/{cat}[{idx}] — not present")
            continue
        e = examples[idx]
        gold = (e.get("gold") or {}).get("text")
        pred = (e.get("pred") or {}).get("text")
        rows.append({
            "model": model.replace("-Few-Shot", " (5s)"),
            "cat": CAT_LABEL.get(cat, cat),
            "type": e.get("entity_type", ""),
            "gold": gold,
            "pred": pred,
            "gloss": GLOSS.get((model, cat, idx), ""),
        })

    lines = [
        "% Auto-generated by scripts/make_error_examples_table.py — do not edit by hand.",
        "\\begin{table*}[ht!]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\caption{Representative extraction errors on the standard benchmark test set, drawn from the "
        "error classification underlying Table~\\ref{tab:error_classification}. Spans are shown verbatim in "
        "Portuguese and truncated for space. The encoder failure mode is truncation of long \\textsc{Subject} "
        "spans, whereas the generative model's boundary errors are systematic over-inclusion: determiners, "
        "honorifics, stance phrases, and administrative framing that the annotation guidelines exclude from "
        "the span. These are precisely the errors that exact match penalises and relaxed match forgives.}",
        "\\label{tab:error_examples}",
        "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} l l l p{0.30\\textwidth} p{0.30\\textwidth} @{}}",
        "\\toprule",
        "\\textbf{Model} & \\textbf{Err} & \\textbf{Type} & \\textbf{Gold span} & \\textbf{Predicted span} \\\\",
        "\\midrule",
    ]

    for r in rows:
        lines.append(
            f"{r['model']} & {r['cat']} & \\textsc{{{r['type'].lower()}}} & "
            f"{esc(r['gold'])} & {esc(r['pred'])} \\\\"
        )
        lines.append(f"\\multicolumn{{5}}{{@{{}}l@{{}}}}{{\\quad\\scriptsize\\textit{{{r['gloss']}}}}} \\\\[2pt]")

    lines += ["\\bottomrule", "\\end{tabular*}", "\\end{table*}", ""]

    out = Path(args.out)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} error examples -> {out}")


if __name__ == "__main__":
    main()
